# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 321f7eb3af3d084972e2c6e49485a8a1344265e63c0070d46b2493207719bfc83f635b5db5e79e11f27107cd94b0f3cb7b5eabac1eef3695438bab729d7635bd

test:
  secret_key_base: 7a8ecae8ea4307c7fb51c2dcca21927da32f20385c763cbee9a0837d5279b6bf9cb2559cdc0ecc8322e6d45ed167500d9e09a24daddfb6665ff10bd89d0ffa74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
